<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Palmtree Form - Collection Example</title>
    <?= get_styles(); ?>
    <style>
        .remove-entry-link {margin-bottom:1rem;}
    </style>
</head>
<body>
<main>
    <div class="container mt-3">
        <h1>Palmtree Form - Collection Example</h1>
        <?php if ($success): ?>
            <div class="alert alert-success">Form submitted successfully</div>
        <?php endif; ?>
        <?= $form->render(); ?>
    </div>
</main>
<?= get_scripts(); ?>
<script src="/dist/palmtree-form.pkgd.js"></script>
</body>
</html>
