<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Palmtree Form - Simple Example</title>
    <?= get_styles(); ?>
</head>
<body>
<main>
    <div class="container mt-3">
        <h1>Palmtree Form - Bootstrap Grid Example</h1>
        <?php if ($success): ?>
            <div class="alert alert-success">Form submitted successfully</div>
        <?php endif; ?>
        <?= $form->renderStart(); ?>
        <div class="row">
            <div class="col-6">
                <?= $form->renderField('first_name'); ?>
            </div>
            <div class="col-6">
                <?= $form->renderField('last_name'); ?>
            </div>
        </div>
        <?= $form->renderRest(); ?>
        <div class="form-group mb-3">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        <?= $form->renderEnd(); ?>
    </div>
</main>
<?= get_scripts(); ?>
</body>
</html>
